version: "3"
services:
    web:
        image: cqrs-scratch
        build:
            context: .
            dockerfile: src/WebApi/Dockerfile
        ports: 
            - "8080:80"
        depends_on: 
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports: 
            - "1433:1433"
        environment: 
            MSSQL_SA_PASSWORD: "M@more123"
            ACCEPT_EULA: "Y"
